### ISSUE TITLE
DartWorker (46): EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by hyunkwak** [BrutalCoding/aub.ai#10]
Hello, I've been trying to run the example app on my phone but I seem to be getting an error. I've tried 2 different models to ensure it's not an issue with the model and also attached a screenshot of the line of code that's resulting in an error. 

iPhone details:
iPhone 13 Pro
iOS Version 17.2.1

Recordings:
https://github.com/BrutalCoding/aub.ai/assets/146910627/979e497e-fdf3-49fa-b4cb-c310a40044ae
https://github.com/BrutalCoding/aub.ai/assets/146910627/99a20707-3d50-402b-8c06-f5872d925325

Screenshot:
<img src="https://github.com/BrutalCoding/aub.ai/assets/146910627/af7a1595-f48a-4745-9bf6-ac5b9f2f7d32" width="300"/>

If you require any further information then please let know 🙂

**Comment by BrutalCoding** [comment]
Hi,

Great to see detailed issues like yours, it helps me get an overall picture quickly.

I had taken a short break from coding in general but I have started getting myself up and running again. I will get back to you on this issue within the next few days.

Cheers,
Daniel

**Comment by BrutalCoding** [comment]
I haven't worked on this issue yet but I just rewatched your 2nd video and noticed the model you were using: Phi-2.

Not sure what other model you tried, but it makes sense to me now that it didn't work for you (neither should anyone else using this repo).

So, the short answer is that my llama.cpp is outdated. To confirm that, you could take a look at the llama.cpp submodule in this repo of mine. There, you'll notice what commit hash of llama.cpp I've used in my last build, and I thought I had covered their patch to support phi-2 but it seems like I was a bit too early. 

I've just started to get myself familiar again (had a break) with the latest progressions.

Expect some new commits this week, this issue should be resolved soon. I'll make sure to test phi-2  too, it's the best model to date I think for mobile devices. 

I wish Mistral had a similar sized model already.

Hope this clarifies your issue. Expect a fix soon.

**Comment by hyunkwak** [comment]
Hello, it's a relief to hear that I wasn't using it incorrect. Thanks for your prompt response and concerted effort on this matter, I look forward to trying out the updated version 🙂

**Comment by BrutalCoding** [comment]
@hyunkwak heya can you give it another try? Make sure to pull the latest changes.

**Comment by hyunkwak** [comment]
@BrutalCoding Thank you so much, I think it's working now 😄 I read about your current situation in the readme, hope that you've managed to find a job/sustainable source of income!

**Comment by BrutalCoding** [comment]
> @BrutalCoding Thank you so much, I think it's working now 😄 I read about your current situation in the readme, hope that you've managed to find a job/sustainable source of income! 

Awesome! Happy to hear that.

I've been getting several sponsorships from various individuals, which I have trouble finding the words for to express my gratitude (heck heah?!).

The amount I receive  in total isn't close to anything sustainable, but I have been approached by a few entities last week that would change that. Happy to say that I'm making a final call this week. Yay!

In case of any issues, feel free to reach out again.

Cheers,
Daniel
