### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by GameOverFlowChart** [BrutalCoding/aub.ai#9]
Hey I have officially run a 7b model on my Android using your app.
```
system
You are a helpful assistant. Be concise and helpful. If you don't know the answer to a question, please don't share false information.
user
What's up?
assistant
Not much, just here to assist you with any questions or information you may need. How can I help you today?
```

It is slower and has less functions (like sampling settings, changing picture, prompt templates) than https://github.com/Mobile-Artificial-Intelligence/maid however I like that you plan to release a standalone plugin that can be used in other projects. For now I will stick with maid but will have an eye on this project.

**Comment by BrutalCoding** [comment]
Thanks for your feedback! 

I have checked out Maid and it seems to be a fork of Sherpa (seen it before), but it was/is abandoned. Maid continued on that repo it seems, but are having issues to update their llama.cpp port. Sherpa/Maid went for a tight integration, just like I initially did with ShadyAI.

I really should allocate time to work on my CI/CD setup for this repo, that'll make this repo synced with llama.cpp's progression on a daily basis. Once done, I think I'll reach out to Maid and see if they can use/contribute to this plugin instead. 

Anyways, once again, thank you. 

Could you please close/resolve this?
